spring.application.name=StreamingAPI

server.port=${PORT:8080}

#spring.data.mongodb.uri=mongodb://localhost:27017/streamingmoviedb
#spring.data.mongodb.database=streamingmoviedb

spring.data.mongodb.uri=mongodb+srv://streammovie_db_user:streammovie_db_password@streamingmoviecluster.mjkbdrn.mongodb.net/?appName=streamingmoviecluster
spring.data.mongodb.database=streamingmoviedb

