spring.application.name=StreamingAPI

server.port=${PORT:8080}

#spring.data.mongodb.uri=mongodb://localhost:27017/mystreamingdb
#spring.data.mongodb.database=mystreamingdb

spring.data.mongodb.uri=mongodb+srv://testuser:testpassword@tonymongodb.u3ajbx2.mongodb.net/?appName=tonymongodb
spring.data.mongodb.database=tonymongodb

